<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Question Paper Generator</title>

    <!-- font awesome cdn link  -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">

    <!-- custom css file link  -->
    <link rel="stylesheet" href="css/style.css?v=<?php echo time();?>">

</head>

<body>

    <?php include 'home_header.php'; ?>

    <section class="home">

        <div class="content">
            <h3>Genrate a question paper <span style="color:var(--red);">for class test</span> <br> in second.</h3>
        </div>

    </section>

    <section class="products">

        <h1 class="title">About Project</h1>

        <div class="content" style="    text-align: center;
    font-size: 2rem;    margin: 0rem 10rem;">
            <p>The Aim of this project is to develop an online appliation/website for the
                Teachers to generate a Model Question papers. The system will be online
                application that can help to increase the question bank which is accessed
                through the Teachers. The user can access the application with proper login provided the system. This
                system can be used as an application by the several
                Teachers of different colleges. </p>
            <p>User registration should be able to upload their information in the form of
                email and system will give a password for logging. The Question papers will be
                of different subjects according to the universities. As the question paper is of 50
                marks or more over the paper will get generated by the system. The questions
                will be descriptive type which will helpful to make the question papers. And
                the new question will be added to the database if the teacher thought it may
                important for the examination
            </p>
        </div>

    </section>






    <?php include 'footer.php'; ?>

    <!-- custom js file link  -->
    <script src="js/script.js"></script>

</body>

</html>